site_name: My Docs
theme:
  name: material
markdown_extensions:
  - def_list
nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'MkDocs': 'userguide\mkdocs.md'
    - 'Git管理': 'userguide\git.md'
    - 'フォルダ構成': 'userguide\folder_structure.md'